
PROMPT ===========================================
PROMPT Create table SMAN$_STORED_OBJECTS
PROMPT ===========================================


  CREATE TABLE "SMAN$_STORED_OBJECTS" 
   (	"CMP_CMP_ID" VARCHAR2(30), 
	"OBJECT_TYPE" VARCHAR2(30), 
	"OBJECT_NAME" VARCHAR2(60), 
	"STORE_DATE" DATE, 
	"LABEL" VARCHAR2(2000), 
	"OBJECT" CLOB, 
	"OBJECT_BODY" CLOB, 
	"OBJECT_DML" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "&&DATA_MD" 
 LOB ("OBJECT") STORE AS (
  TABLESPACE "&&DATA_MD" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB ("OBJECT_BODY") STORE AS (
  TABLESPACE "&&DATA_MD" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB ("OBJECT_DML") STORE AS (
  TABLESPACE "&&DATA_MD" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) ;
 
PROMPT ===========================================
PROMPT Add comments on SMAN$_STORED_OBJECTS
PROMPT ===========================================


   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."CMP_CMP_ID" IS 'Component id';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."OBJECT_TYPE" IS 'Schema-object type';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."OBJECT_NAME" IS 'Schema-object name';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."STORE_DATE" IS 'Date/time when it was stored';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."LABEL" IS 'Label';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."OBJECT" IS 'Object code';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."OBJECT_BODY" IS 'Object body code (packages, types) or table constraints';
 
   COMMENT ON COLUMN "SMAN$_STORED_OBJECTS"."OBJECT_DML" IS 'Object DML (only tables)';
 