
PROMPT ===========================================
PROMPT Create indexes on SMAN$_PARAMETER
PROMPT ===========================================


  CREATE UNIQUE INDEX "SMAN$_PARAM_NAME_PK" ON "SMAN$_PARAMETER" ("PARAM_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD" ;
 
PROMPT ===========================================
PROMPT Add constraints on SMAN$_PARAMETER
PROMPT ===========================================


  ALTER TABLE "SMAN$_PARAMETER" ADD CONSTRAINT "SMAN$_PARAM_NAME_PK" PRIMARY KEY ("PARAM_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD"  ENABLE;
 
  ALTER TABLE "SMAN$_PARAMETER" MODIFY ("PARAM_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SMAN$_PARAMETER" MODIFY ("PARAM_VALUE" NOT NULL ENABLE);
 