
PROMPT ===========================================
PROMPT Create indexes on SMAN$_COMPONENT
PROMPT ===========================================


  CREATE UNIQUE INDEX "SMAN$_CMP_PK" ON "SMAN$_COMPONENT" ("CMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD" ;
 
PROMPT ===========================================
PROMPT Add constraints on SMAN$_COMPONENT
PROMPT ===========================================


  ALTER TABLE "SMAN$_COMPONENT" ADD CONSTRAINT "SMAN$_CMP_PK" PRIMARY KEY ("CMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD"  ENABLE;
 
  ALTER TABLE "SMAN$_COMPONENT" MODIFY ("CMP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SMAN$_COMPONENT" MODIFY ("CMP_DESC" NOT NULL ENABLE);
 