
PROMPT ===========================================
PROMPT Create indexes on SMAN$_OBJECT_CONFIG
PROMPT ===========================================


  CREATE UNIQUE INDEX "SMAN$_OBJECT_CONFIG_PK" ON "SMAN$_OBJECT_CONFIG" ("OBJECT_TYPE", "OBJECT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD" ;
 
PROMPT ===========================================
PROMPT Add constraints on SMAN$_OBJECT_CONFIG
PROMPT ===========================================


  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK" CHECK (OBJECT_TYPE IN ('DB_LINK','FUNCTION','MATERIALIZED VIEW','PACKAGE','PROCEDURE','SEQUENCE','SYNONYM','TABLE','TRIGGER','TYPE','VIEW')) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK1" CHECK ((OBJECT_TYPE = 'TABLE') OR (OBJECT_TYPE != 'TABLE' AND GENERATE_DML IS NULL)) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK2" CHECK (GENERATE_DML = 'T' OR GENERATE_DML IS NULL) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK3" CHECK ((OBJECT_TYPE NOT IN ('SYNONYM','TRIGGER')) OR (OBJECT_TYPE IN ('SYNONYM','TRIGGER') AND CREATE_PUBLIC_SYNONYM IS NULL)) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK4" CHECK (CREATE_PUBLIC_SYNONYM = 'T' OR CREATE_PUBLIC_SYNONYM IS NULL) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK5" CHECK ((OBJECT_TYPE NOT IN ('SYNONYM','TRIGGER')) OR (OBJECT_TYPE IN ('SYNONYM','TRIGGER') AND GENERATE_GRANTS IS NULL)) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK6" CHECK (GENERATE_GRANTS = 'T' OR GENERATE_GRANTS IS NULL) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CHK7" CHECK (OBJECT_NAME = upper(OBJECT_NAME)) ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_PK" PRIMARY KEY ("OBJECT_TYPE", "OBJECT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "&&DATA_MD"  ENABLE;
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" MODIFY ("CMP_CMP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SMAN$_OBJECT_CONFIG" ADD CONSTRAINT "SMAN$_OBJECT_CONFIG_CMP_FK" FOREIGN KEY ("CMP_CMP_ID")
	  REFERENCES "SMAN$_COMPONENT" ("CMP_ID") ENABLE;
 